RH.View/Controllers/ProvaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.Model;
using RH.Control;
using System.Drawing;
using System.IO;
using System.Drawing.Imaging;
using RH.View.Filtro;

namespace RH.View.Controllers
{
    
    public class ProvaController : Controller
    {
        CProva _Control;

        public ProvaController()
        {
            _Control = new CProva();
        }

        public string SelecionarNome()
        {
            string[] Nomes = new string[100] { "Abílio Carneiro",
            "Adalberto Fernández",
            "Adelaide Junqueira",
            "Adelaide Vilanova",
            "Adelina Angelim",
            "Aida Cortês",
            "Américo Mariz",
            "Amílcar Belén",
            "Angelino Cayubi",
            "Anna Taperebá",
            "António Muniz",
            "Aníbal Leal",
            "Berengária Brandão",
            "Bernardina Godoi",
            "Boaventura Castella",
            "Brenda Conceição",
            "Bukake Canhão",
            "Bukake Maranhão",
            "Burtira Pinheiro",
            "Caetano Ferreyra",
            "Carolina Borges",
            "Casimiro Rangel",
            "Caubi Covilhã",
            "Cauã Suaçuna",
            "Cândida Barreto",
            "Davide Valentín",
            "Deise Baranda",
            "Delfina Bacelar",
            "Délia Durão",
            "Ema Uchoa",
            "Emiliana Teves",
            "Estefânia Carreiro",
            "Eugénia Sanches",
            "Evangelista Maciel",
            "Evaristo Dourado",
            "Filipa Giménez",
            "Flávio Vilarim",
            "Frederico Mirandela",
            "Fábia Torcato",
            "Godofredo Athayde",
            "Graça Guará",
            "Gregório Xavier",
            "Guido Freitas",
            "Guilhermina Carromeu",
            "Guiomar Guimaraens",
            "Gávio Lagos",
            "Helena Barroqueiro",
            "Herberto Diniz",
            "Hermígio Beltrão",
            "Hernâni Moreira",
            "Ifigénia Vides",
            "Jacira Silveira dos Açores",
            "Jandira Beltrão",
            "Jerónimo, Jerônimo Junquera",
            "Jerónimo, Jerônimo Sant'Anna",
            "Joaquim Bencatel",
            "Joaquim Gentil",
            "Jónatas Sousa de Arronches",
            "Júlio Salazar",
            "Luciano Montero",
            "Lucinda Siebra",
            "Luísa Lage",
            "Lília Carrasqueira",
            "Mafalda Perdigón",
            "Mafalda Tabosa",
            "Mamede Maciel",
            "Mbicy Maciel",
            "Morgana Candeias",
            "Natividade Rivas",
            "Odilia Jorge",
            "Palmira Cardozo",
            "Pandora Díaz",
            "Quirino Briones",
            "Raquel Goes",
            "Raquel Ríos",
            "Romano Lamego",
            "Roque Jucá",
            "Rui Villaverde",
            "Rúben Roriz",
            "Salomão Marroquim",
            "Salvina Fialho",
            "Sebastião Gutiérrez",
            "Severino Tupinambá",
            "Sofia Marinho",
            "Solano Inês",
            "Suniário Liberato",
            "Tadeu Padilha",
            "Taíssa Viegas",
            "Ubirajara Camilo",
            "Ubiratã Ribas",
            "Udo Varella",
            "Vanessa Piratininga",
            "Viriato Cachão",
            "Vitória Ornellas",
            "Vânia Talhão",
            "Xênia Parracho",
            "Zeferino Açores",
            "Zélia Domínguez",
            "Átila Ávila",
            "Énia Viveros"
            };

            int posicao;

            Random random = new Random();
            posicao = random.Next(0, 99);

            return Nomes[posicao];
        }

        public string SelecionarEndereco()
        {
            string[] Enderecos = new string[80]
            {
                    "Vila Verde",
                    "Novo Surubi",
                    "Surubi",
                    "Jardim Esperança",
                    "Morada da Barra",
                    "Jardim do Sol",
                    "Parque Embaixador",
                    "Fazenda da Barra 1",
                    "Fazenda da Barra 2",
                    "Fazenda da Barra 3",
                    "Nossa Senhora de Fátima",
                    "Campo Belo",
                    "Maria Cândida",
                    "Isaac Politi",
                    "Morro do Batista",
                    "Morro do Machado",
                    "Vila Moderna",
                    "Jardim Brasília 1",
                    "Jardim Brasília 2",
                    "Parque Ipiranga 1",
                    "Parque Ipiranga 2",
                    "Morada das Garças",
                    "Vicentina",
                    "Santo Amaro",
                    "Eucaliptal",
                    "Terras Alpha",
                    "Vila Julieta",
                    "Santa Cecília",
                    "Jardim Jalisco",
                    "Liberdade",
                    "Nova Liberdade",
                    "Manejo",
                    "Vila Santa Isabel",
                    "Elite",
                    "Morada da Felicidade",
                    "Baixada da Olaria",
                    "Itapuca",
                    "Residencial Limeira",
                    "Morada da Colina 1",
                    "Morada da Colina 2",
                    "Morada da Colina 3",
                    "Mirante das Agulhas",
                    "Residencial Morada das Agulhas",
                    "Morada do Bosque",
                    "Casa da Lua",
                    "Loteamento Cícero",
                    "Alegria 1",
                    "Alegria 2",
                    "Nova Alegria",
                    "Jardim Alegria",
                    "Cidade Alegria",
                    "Nova Resende",
                    "Boa Vista 1",
                    "Boa Vista 2",
                    "Mirante da Serra",
                    "Morada da Montanha",
                    "Morada do Contorno",
                    "Jardim Beira Rio",
                    "Vila Isabel",
                    "Primavera 1",
                    "Primavera 2",
                    "Primavera 3",
                    "Jardim Aliança",
                    "Jardim do Oeste",
                    "Morada do Castelo",
                    "Montese",
                    "Bairro Comercial",
                    "Monte Castelo",
                    "Guararapes",
                    "Independência",
                    "Cabral",
                    "Alambari",
                    "Paraíso",
                    "Castelo Branco",
                    "Morro do Cruzeiro",
                    "Vila Araújo",
                    "Comercial",
                    "Jardim Tropical",
                    "São Caetano",
                    "Monet"
            };

            int posicao;

            Random random = new Random();
            posicao = random.Next(0, 79);

            return Enderecos[posicao];
        }

        [AutorizacaoProfessor]
        // GET: Prova
        public ActionResult Index()
        {
            List<Aluno> Alunos = _Control.SelecionarTodosAlunos();
            ViewBag.QuantidadeAlunos = Alunos.Count();

            List<VW_Provas> Provas = _Control.SelecionarTodasProva();
            return View(Provas);
        }

        [AutorizacaoProfessor]
        public ActionResult CadastrarProva(string DataTermino)
        {
            bool ProvaAtiva = _Control.ProvaAtiva();
            if(ProvaAtiva)
            {
                return Json("3");
            }

            DateTime Data = Convert.ToDateTime(DataTermino);

            if (DateTime.Compare(DateTime.Now.Date, Data) == 0)
            {
                return Json("0");
            }

            else if (DateTime.Compare(Data, DateTime.Now.Date) < 0)
            {
                return Json("1");
            }

            byte[] data;
            
            var caminho = Server.MapPath("~/Imagem/sem-imagem-avatar.png");
            Bitmap bmp = new Bitmap(caminho);

            MemoryStream memory = new MemoryStream();
            bmp.Save(memory, ImageFormat.Bmp);

            data = memory.ToArray();

            List<Aluno> Alunos = _Control.SelecionarTodosAlunos();


            int CodigoProva = _Control.QuantidadeProvas()+1;

            foreach(var x in Alunos)
            {

                Prova aProva = new Prova();
                Professor oProfessor = (Professor)Session["User"];
                aProva.Pro_Professor_Pro_ID = oProfessor.Pro_ID;
                aProva.Pro_Aluno_Alu_ID = x.Alu_ID;
                aProva.Pro_DataInicio = DateTime.Now;
                aProva.Pro_DataTermino = Convert.ToDateTime(DataTermino);

                int IDAlunoProva = 0;
                Aluno oAluno = _Control.AlunoProva();
                if(oAluno==null)
                {
                    Aluno AlunoProva = new Aluno();
                    AlunoProva.Alu_Curso_Cur_ID = 1;
                    AlunoProva.Alu_DataCadastro = DateTime.Now;
                    AlunoProva.Alu_Email = "ALUNO PROVA";
                    AlunoProva.Alu_Matricula = 1;
                    AlunoProva.Alu_Nome = "ALUNO PROVA";
                    AlunoProva.Alu_Senha = "ALUNO PROVA";
                    AlunoProva.Alu_Serie = 1;
                    AlunoProva.Alu_Situation = false;
                    _Control.CadastrarAluno(AlunoProva);
                    IDAlunoProva = AlunoProva.Alu_ID;
                }

                else
                {
                    IDAlunoProva = oAluno.Alu_ID;
                }

                Empresa aEmpresa = _Control.EmpresaAlunoProva();
                int IDEmpresaProva;

                if(aEmpresa==null)
                {
                    Empresa EmpresaAlunoProva = new Empresa();
                    EmpresaAlunoProva.Emp_Nome = "EMPRESA";

RH.View/Views/Prova/Erros.cshtml
@model IEnumerable<RH.Model.Erro>

@{
    ViewBag.Title = "Erros da Prova";
    Layout = "~/Views/Shared/LayoutSemMenu.cshtml";
    int Erro = 1;
}

<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">@ViewBag.NomeAluno - @ViewBag.MatriculaAluno</h3>
            <h3 class="text-center">@ViewBag.Curso - @ViewBag.Serie</h3>
            <br />
            <h2 class="text-center text-danger">Nota da Prova: @Math.Round(ViewBag.Nota,2)</h2>
            <br />
            <p class="text-danger text-center"><b>Atenção: </b>Caso encontre alguma anomalia na correção de sua prova, por favor entre em contato o mais rápido possível com seu professor.</p>
        </div>
        <div class="card-body">
            @foreach (var x in Model)
            {
                <h5>@Erro º Erro</h5>
                <hr />
                <div class="row">
                    @if (x.Err_RespostaAluno == "Nenhum dos seus benefícios cadastrados se compara ao benefício da prova.")
                    {
                        <div class="col-md-6">
                            <div class="card border-0">

                                <h5>Sua Resposta:</h5>
                                <div class="card-header alert-danger">
                                    @Html.Raw(x.Err_RespostaAluno)
                                    <span class="MeusBeneficios float-right" data-id="@Erro"><i class="fas fa-align-justify"></i></span>
                                </div>

                                <div class="card-body BodyBeneficios alert-danger" id="@Erro" style="display:none;">
                                    <p class="text-center">Meus Benefícios</p>
                                    @foreach(var beneficio in ViewBag.MeusBeneficios)
                                    {
                                        <hr />
                                        <span>Benefício:</span>
                                        <br />
                                        <span>Nome do Benefício: @beneficio.Ben_Nome</span>
                                        <br />
                                        <span>Descrição: @beneficio.Ben_Descricao</span>
                                        <br />
                                        <span>Custo: @beneficio.Ben_Custo</span>
                                        <br />
                                        <span>Data de Cadastro: @beneficio.Ben_DataCadastro</span>
                                        <br />
                                        <br />
                                        <hr />
                                    }
                                </div>
                            </div>
                        </div>
                    }

                    else
                    {
                        <div class="col-md-6">
                            <h5>Sua Resposta:</h5>
                            <div class="alert alert-danger" role="alert">
                                @Html.Raw(x.Err_RespostaAluno)
                            </div>
                        </div>
                    }


                    <div class="col-md-6">
                        <h5>Resposta Certa:</h5>
                        <div class="alert alert-success" role="alert">
                            @Html.Raw(x.Err_RespostaCerta)
                        </div>
                    </div>

                </div>
                <hr />
                <br />
                <br />

                Erro++;

            }
        </div>
    </div>
</div>




@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var posicao = false;

            $(".MeusBeneficios").click(function () {

                var id = $(this).attr("data-id");

                $("#" + id).slideToggle("1000");

            });

        });
    </script>
}

RH.View/Views/Prova/Index.cshtml
@model IEnumerable<RH.Model.VW_Provas>

@{
    /**/

    ViewBag.Title = "Provas";
    Layout = "~/Views/Shared/_Layout_Professor.cshtml";
}
@*<style>
        .modal {
            text-align: center;
        }

            .modal:before {
                content: '';
                display: inline-block;
                height: 100%;
                vertical-align: middle;
                margin-right: -4px;
            }

        .modal-dialog {
            display: inline-block;
            text-align: left;
            vertical-align: middle;
        }
    </style>*@

@Styles.Render("~/Content/Pages/css")
@Styles.Render("~/Content/css")

<br />
<br />
<button class="btn btn-success custom" id="AbrirModal"><i class="fas fa-user-plus"></i> Cadastrar Prova</button>
<br />
<h2 class="text-center">Provas Cadastradas</h2>
<hr />
<div id="ProvasCadastradas">
    @if (Model.Count() > 0)
    {
        foreach (var x in Model)
        {
            <div class="container my-4">
                <div class="card">
                    <div class="card-header">
                        <h2>Código da Prova: @x.CodigoProva</h2>
                    </div>

                    <div class="card-body">
                        <h2>
                            Data de Cadastro: @x.DataCadastro.Day/@if (x.DataCadastro.Month.ToString().Count() == 1)
                            {<span>0</span>}@x.DataCadastro.Month/@x.DataCadastro.Year
                        </h2>
                        <h2>Data de Termino: @x.DataTermino.Date</h2>
                        <h2>Quantidade de Provas Geradas: @x.QuantidadeProvas</h2>
                    </div>

                    @if (DateTime.Compare(x.DataTermino, DateTime.Now.Date) < 0)
                    {
                        <div class="card-footer">
                            <a class="btn btn-danger custom" href="@Url.Action("Notas","Prova",new { CodigoProva=x.CodigoProva})"><span class="fa fa-eye"></span> Visualizar Notas</a>
                        </div>
                    }

                </div>
            </div>
        }
    }

    else
    {
        <div class="alert alert-primary" id="Aviso">
            <div class="alert-body">
                <h4>Não existem provas cadastradas...</h4>
            </div>
        </div>
    }
</div>

<hr>


<div class="modal fade" tabindex="-1" role="dialog" id="ModalCadastrarProva">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cadastrar Prova</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="Mensagem">
                    <h4 class="text-center">Atenção</h4>
                    <p>Ao clicar em "Cadastrar Provas", o sistem a irá gerar o total de @ViewBag.QuantidadeAlunos provas, isso poderá demorar um pouco, então por favor não feche ou reinicie a página enquanto o processo estiver em execução.</p>
                    <div align="center">
                        <h4>Selecione a data de termino da prova</h4>
                        <input type="date" id="DataFim" class="align-content-center form-control col-md-5" />
                    </div>

                </div>

                <div id="Resposta">

                </div>

                <div id="Carregando" align="center" style="display:none;">
                    <img src="~/Imagem/833.gif" />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success BtnModal" id="CadastrarProva" disabled="disabled"><span class="fa fa-plus"></span> Cadastrar Provas</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {

            $("#AbrirModal").click(function () {

                $("#ModalCadastrarProva").modal('show');

                $("#Resposta").css("display", "none");
                $("#Mensagem").css("display", "block");
                $("#DataFim").val("");
                $("#CadastrarProva").attr("disabled", "disabled");
            });

            $("#DataFim").change(function () {

                if ($(this).val() != "") {
                    $("#CadastrarProva").removeAttr('disabled');
                }

                else {
                    $("#CadastrarProva").attr('disabled', 'disabled');
                }

            });

            $("#CadastrarProva").click(function () {
                $(this).attr("disabled", "disabled");
                $("#Carregando").css("display", "block");
                $("#Mensagem").css("display", "none");
                var url = "@Url.Action("CadastrarProva","Prova")";
                var Data = $("#DataFim").val();
                $.post(url, { DataTermino: Data }, function (resposta) {

                    $("#Carregando").css("display", "none");
                    $("#Resposta").css("display", "block");

                    if (resposta == "3") {
                        $("#Resposta").html("<p class='text-center'>Você não pode cadastrar outra prova enquanto outra prova estiver ativa.</p>")
                    }

                    else if (resposta == "0") {
                        $("#Resposta").html("<p class='text-center'>A Data de Termino não pode terminar no dia de hoje</p> <div align='center'> <input type='date' id='DataFim' class='align-content-center form-control col-md-5'/></div>");
                    }

                    else if (resposta == "1") {
                        $("#Resposta").html("<p class='text-center'>A Data de Termino não pode ser um dia que já passou</p> <div align='center'> <input type='date' id='DataFim' class='align-content-center form-control col-md-5'/></div>");
                    }

                    else {

                        $("#Aviso").css("display", "none");

                        var data = new Date();
                        var dia = data.getDate();
                        dia = (dia.length == 1) ? "0" + dia : dia;
                        var mes = data.getMonth() + 1;
                        mes = (mes.length == 1) ? "0" + mes : mes;
                        var ano = data.getFullYear();

                        var DataTermino = new Date(Data);
                        var diaTermino = DataTermino.getDate() + 1;
                        diaTermino = (diaTermino.length == 1) ? "0" + diaTermino : diaTermino;
                        var mesTermino = DataTermino.getMonth() + 1;
                        mesTermino = (mesTermino.length == 1) ? "0" + mesTermino : mesTermino;
                        var DataFormatada = [diaTermino, mesTermino, DataTermino.getFullYear()].join("/");


                        $("#Resposta").html("<p class='text-center'>Provas Cadastradas com sucesso!</p>");

                        $("#ProvasCadastradas").append("<div class='container my-4'>" +
                            "<div class='card'>" +
                            "<div class='card-header'>" +
                            "<h2>Código da Prova:Teste</h2>" +
                            "</div>" +

                            "<div class='card-body'>" +
                            "<h2>Data de Cadastro:" + dia + "/" + mes + "/" + ano + "</h2>" +
                            "<h2>Data de Termino: " + DataFormatada + " 00:00:00</h2>" +
                            "<h2>Quantidade de Provas Geradas: " + @ViewBag.QuantidadeAlunos + "</h2>" +
                            "</div>" +
                            "</div>" +
                            "</div>"
                        );
                    }

                    $("#CadastrarProva").attr("disabled", "disabled");


                });
            });



        })

    </script>
}

RH.View/Views/Prova/Notas.cshtml
@model IEnumerable<RH.Model.VW_Notas>

@{
    ViewBag.Title = "Notas da Prova";
    Layout = "~/Views/Shared/_Layout_Professor.cshtml";
}

<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">Notas das provas da turma de @Model.Select(p=>p.Curso).First() - @Model.Select(p=>p.SerieAluno).First()º Ano</h3>
        </div>
        <div class="card-body">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered text-center table-hover">
                    <tr style="background-color: rgb(148,72,72);" class="text-white">
                        <th>
                            Código
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            Matrícula
                        </th>
                        <th>
                            Curso
                        </th>
                        <th>
                            Série
                        </th>
                        <th>
                            Data de Entrega
                        </th>
                        <th>
                            Nota da Prova
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CodigoProva)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomeAluno)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MatriculaAluno)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Curso)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SerieAluno) º Ano
                        </td>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.Entregou)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NotaProva)
                        </td>
                    </tr>
                    }

                </table>
            }

        </div>
    </div>
</div>