RH.View/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.Model;
using RH.Control;
using RH.View.Filtro;
using PagedList;
using RH.View.CriptoHelper;

namespace RH.View.Controllers
{
    [AutorizacaoEmpresa]
    public class CargoController : Controller
    {
        private CCargo _Control;

        public CargoController()
        {
            _Control = new CCargo();
        }
        
        // GET: Cargo
        public ActionResult Index(int? pagina,string Pesquisa="")
        {
            ViewBag.Pesquisado = null;
            List<Cargo> _cargos = _Control.SelecionarTodosCargosEmpresa(Convert.ToInt32(Session["IDEmpresa"]));

            if(!string.IsNullOrEmpty(Pesquisa))
            {
                _cargos = _cargos.Where(p => p.Car_Nome.Contains(Pesquisa)).ToList();
                ViewBag.Pesquisado = Pesquisa;
            }

            int paginaTamanho = 4;
            int paginaNumero = (pagina ?? 1);

            return View(_cargos.ToPagedList(paginaNumero,paginaTamanho));
        }


        public ActionResult CadastrarCargo()
        {
            List<Setor> Setores = _Control.SelecionarSetoresEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
            ViewBag.Car_Setor_Set_ID = new SelectList(Setores, "Set_ID", "Set_Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarCargo(Cargo oCargo,bool ChefeSetor)
        {
            List<Setor> Setores = _Control.SelecionarSetoresEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
            ViewBag.Car_Setor_Set_ID = new SelectList(Setores, "Set_ID", "Set_Nome");

            bool EmpresaAvaliativa = Convert.ToBoolean(Session["Avaliativa"]);

            if (EmpresaAvaliativa)
            {
                if (_Control.LimiteCargosEmpresaAvaliativa(Convert.ToInt32(Session["IDEmpresa"])))
                {
                    ModelState.AddModelError("Limite", "O limite de cargos nessa Empresa Avaliativa foi atingido. (Limite de Cargos = 5)");
                }
            }

                if (ChefeSetor)
            {
                bool StatusChefe = _Control.SelecionarChefeSetor(oCargo.Car_Setor_Set_ID);
                if (StatusChefe)
                {
                    ModelState.AddModelError("ChefeSetor", "Este setor já possui um chefe, troque o status de chefe do cargo ou selecione outro setor de atividade");
                    return View();
                }
            }

            bool CargosComMesmoNome = _Control.CargosComMesmoNome(oCargo.Car_Nome, oCargo.Car_Setor_Set_ID);
            if (CargosComMesmoNome)
            {
                ModelState.AddModelError("Car_Nome", "Este setor já possui um cargo com este nome");
                return View();
            }

            if (ModelState.IsValid)
            {
                Empresa aEmpresa = _Control.SelecionarEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
                oCargo.Car_DataCadastro = aEmpresa.Emp_DataAtual;
                oCargo.Car_Chefe = ChefeSetor;
                oCargo.Car_Situation = true;
                _Control.CadastrarCargo(oCargo);
                return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult AlterarCargo(string id)
        {
            int IDDescriptografado = Convert.ToInt32(Criptografia.DecriptQueryString(id));

            List<Setor> Setores = _Control.SelecionarSetoresEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
            
            Cargo oCargo = _Control.SelecionarCargo(IDDescriptografado);

            ViewBag.Car_Setor_Set_ID = new SelectList(Setores, "Set_ID", "Set_Nome", oCargo.Car_Setor_Set_ID);

            return View(oCargo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarCargo(Cargo oCargo,bool ChefeSetor)
        {
            List<Setor> Setores = _Control.SelecionarSetoresEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
            ViewBag.Car_Setor_Set_ID = new SelectList(Setores, "Set_ID", "Set_Nome", oCargo.Car_Setor_Set_ID);

            Cargo oCargo1 = _Control.SelecionarCargo(oCargo.Car_ID);

            if (!oCargo1.Car_Chefe && ChefeSetor)
            {
                bool StatusChefe = _Control.SelecionarChefeSetor(oCargo.Car_Setor_Set_ID);
               
                if (StatusChefe)
                {
                    ModelState.AddModelError("ChefeSetor", "Este setor já possui um chefe, troque o status de chefe do cargo ou selecione outro setor de atividade");
                    return View(oCargo);
                }
            }

            bool CargosComMesmoNome = _Control.CargosComMesmoNome(oCargo.Car_Nome, oCargo.Car_Setor_Set_ID);
            if (CargosComMesmoNome && oCargo.Car_Setor_Set_ID != oCargo1.Car_Setor_Set_ID)
            {
                ModelState.AddModelError("Car_Nome", "Este setor já possui um cargo com este nome");
                return View(oCargo);
            }


            if (ModelState.IsValid)
            {
                
                oCargo1.Car_Nome = oCargo.Car_Nome;
                oCargo1.Car_Setor_Set_ID = oCargo.Car_Setor_Set_ID;
                oCargo1.Car_Chefe = ChefeSetor;
                _Control.AlterarCargo(oCargo1);

                return RedirectToAction("Index");
            }

            return View(oCargo);
        }

        public ActionResult ExcluirCargo(int id)
        {
            Cargo oCargo = _Control.SelecionarCargo(id);

            Pessoa aPessoa = _Control.SelecionarPessoaCargo(id);

            if (aPessoa != null)
            {
                return Json("Não é possivel escluir esse cargo, pois existem funcionários cadastrados nesse cargo, por favor antes de excluir esse cargo exclua os funcionários que estão cadastrados no mesmo");
            }

            else
            {
                oCargo.Car_Situation = false;
                _Control.ExcluirCargo(oCargo);
                return Json("O cargo foi excluído com sucesso!");
            }

            
        }

    }
}

RH.View/Views/Cargo/AlterarCargo.cshtml
@model RH.Model.Cargo

@{
    ViewBag.Title = "AlterarCargo";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Car_ID)

        <div class="form-row">

            <div class="container my-4">
                <div class="card">
                    <div class="card-header">
                        <h1>Alterar Cargo</h1>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Car_Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Car_Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Car_Nome, "", new { @class = "text-danger" })
                            </div>

                            <div class="col-md-12">
                                @Html.LabelFor(model => model.Car_Setor_Set_ID, "Setor pertencente", htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownList("Car_Setor_Set_ID", null, "Selecione o setor que o cargo pertence", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Car_Setor_Set_ID, "", new { @class = "text-danger" })
                            </div>
                            <br />
                            <div class="text-center">
                                @Html.LabelFor(model => model.Car_Chefe, "Este cargo ocupa a posição de chefe do setor?", htmlAttributes: new { @class = "control-label text-center" })
                                <br />
                                @if (Model.Car_Chefe)
                                {
                                    <label><input type="radio" value="true" name="ChefeSetor" checked /> Sim</label>
                                    <label><input type="radio" value="false" name="ChefeSetor" /> Não</label>
                                }

                                else
                                {
                                    <label><input type="radio" value="true" name="ChefeSetor" /> Sim</label>
                                    <label><input type="radio" value="false" name="ChefeSetor" checked /> Não</label>
                                }
                                <br />
                                @Html.ValidationMessage("ChefeSetor", "", new { @class = "text-danger" })
                            </div>

                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group">
                            <div class="form-group col-md-6 ">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Salvar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />

                <div class="back">
                    <a href="~/Cargo/Index"><i class="fas fa-arrow-left"></i> Voltar</a>
                </div>

            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.Car_DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Car_DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Car_DataCadastro, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.Car_Situation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Car_Situation)
                    @Html.ValidationMessageFor(model => model.Car_Situation, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RH.View/Views/Cargo/CadastrarCargo.cshtml
@model RH.Model.Cargo

@{
    ViewBag.Title = "CadastrarCargo";

    if (ViewBag.Setores == null)
    {
        ViewBag.Setores = "";
    }
}

@Styles.Render("~/Content/Pages/css")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    </div>

    <div class="container my-4">
        <div class="card">
            <div class="card-header">
                <h1>Cadastrar Cargo</h1>
            </div>
            <div class="card-body">
                <div align="center">
                    @Html.ValidationMessage("Limite", "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Car_Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Car_Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Car_Nome, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-12">
                        @Html.LabelFor(model => model.Car_Setor_Set_ID, "Setor pertencente", htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownList("Car_Setor_Set_ID", null, "Selecione o setor que o cargo pertence", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Car_Setor_Set_ID, "", new { @class = "text-danger" })
                    </div>
                    <br />
                    <div class="text-center">
                        @Html.LabelFor(model => model.Car_Chefe, "Este cargo ocupa a posição de chefe do setor?", htmlAttributes: new { @class = "control-label text-center" })
                        <br />
                        <label><input type="radio" value="true" name="ChefeSetor" checked /> Sim</label>
                        <label><input type="radio" value="false" name="ChefeSetor" /> Não</label>
                        <br />
                        @Html.ValidationMessage("ChefeSetor", "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="card-footer">
                <div class="form-group">
                    <div class="form-group col-md-6 ">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Cadastrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        
        <div class="back">
            <a href="~/Cargo/Index"><i class="fas fa-arrow-left"></i> Voltar</a>
        </div>

    </div>
}



<div class="modal fade" tabindex="-1" role="dialog" id="ModalSetor">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Demitir funcionário</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-center">@ViewBag.Cargos</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn bg-success text-white" data-dismiss="modal" id="BtnNao">Ok</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

    $(document).ready(function () {

        $("#ModalSetor").on('hide.bs.modal', function () {
            $(location).attr("href", "@Url.Action("CadastrarCargo","Cargo")");
        });


    });
    </script>

    @if (ViewBag.Setores != "")
    {
        <script>
            $("#ModalSetor").modal('show');
        </script>
    }
}

RH.View/Views/Cargo/Index.cshtml
@model PagedList.IPagedList<RH.Model.Cargo>

@{
    /**/

    ViewBag.Title = "Meus Cargos";
}
@Styles.Render("~/Content/Pages/css")
@using PagedList.Mvc
@using RH.View.CriptoHelper;


<br />
<p>
    <a class="btn btn-success custom" href="@Url.Action("CadastrarCargo","Cargo")"><i class="fas fa-plus"></i> Cadastrar Novo Cargo</a>
</p>



@using (Html.BeginForm("Index", "Cargo", FormMethod.Get))
{
    <div class="input-group col-md-4 float-right">

        @if (!string.IsNullOrEmpty(ViewBag.Pesquisado))
        {
            <input type="text" class="form-control" name="Pesquisa" value="@ViewBag.Pesquisado" placeholder="Pesquisar cargos">
        }

        else
        {
            <input type="text" class="form-control" name="Pesquisa" placeholder="Pesquisar cargos">
        }

        <div class="input-group-append">
            <button class="btn btn-success custom" type="submit"><span class="fa fa-search"></span></button>
        </div>
    </div>
}

<br />
<br />

<h2 class="text-center">Cargos Cadastrados</h2>

<hr />
@if (ViewBag.Pesquisado != null && Model.Count() == 0)
{
    <div class="alert alert-primary">
        <div class="alert-body">
            <h4>Não foi encontrado nenhum resultado referente a pesquisa '@ViewBag.Pesquisado', verifique o que foi digitado e tente novamente.</h4>
        </div>
    </div>
}

else
{
    if (Model.Count() > 0)
    {
        <div class="container">
            @foreach (var x in Model)
            {

                <div class="row">
                    <div class="col-md-12">

                        <div class="card" id="Cargo-@x.Car_ID">
                            <div class="card-header"><h4>Nome:<span class='textUser'> @x.Car_Nome</span></h4></div>
                            <div class="card-body bg-light">
                                <div class="row">
                                    <div class="col-md-6 text-center">
                                        <p><h4>Setor do Cargo: <span class='textUser'>@Html.DisplayFor(modelItem => x.Setor.Set_Nome)</span></h4></p>
                                        <p><h4>Data de Cadastro:<span class='textUser'> @x.Car_DataCadastro</span></h4></p>
                                        <p>
                                            <h4>
                                                @if (x.Car_Chefe)
                                                {
                                                    <span>Chefe do setor</span>
                                                }

                                                else
                                                {
                                                    <span>Funcionário</span>
                                                }
                                            </h4>
                                        </p>
                                    </div>
                                    <div class="col-md-6 text-white text-right">
                                        <a class="btn btn-warning custom" href="@Url.Action("AlterarCargo","Cargo",new { id=Criptografia.EncryptQueryString(x.Car_ID.ToString())})"><i class="fas fa-pencil-alt"></i> Alterar Cargo</a>
                                        <button class="btn btn-danger custom AbrirModal" data-id="@x.Car_ID"><i class="fas fa-trash-alt"></i> Excluir Cargo</button>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <br />


            }
            <nav aria-label="Page navigation example " class="paginacao">
                <ul class="pagination">
                    <li class="page-item">
                        @Html.PagedListPager(Model, page => Url.Action("index", new { pagina = page }))

                    </li>
                </ul>
            </nav>

        </div>
    }

    else
    {
        <div class="alert alert-primary">
            <div class="alert-body">
                <h4>Esta empresa ainda não possui nenhum cargo cadastrado...</h4>
            </div>
        </div>
    }
}



<hr />

<div class="modal fade" tabindex="-1" role="dialog" id="ModalExcluir">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir Cargo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="Confirmacao"></p>
                <div align="center">
                    <img src="~/Imagem/833.gif" id="Carregando" style="display:none;" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning custom" id="Excluir">Sim</button>
                <button type="button" class="btn btn-danger custom" data-dismiss="modal" id="BtnNao">Não</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>

        var clicksAbrirModal = 0;

        console.log("ola")

        document.querySelector("#ModalExcluir").addEventListener('click', () => {
            console.log(clicksAbrirModal);
            clicksAbrirModal++;
        });




        window.addEventListener('click', function (e) {
            var mouse = {
                page: {
                    x: e.pageX,
                    y: e.pageY
                },
                client: {
                    x: e.clientX,
                    y: e.clientY
                }
            }
            console.log(mouse.page.y);





            if (clicksAbrirModal == 0) {
                document.querySelector(".modal-dialog").style.marginTop = (mouse.page.y - 120) + "px";
                console.log(clicksAbrirModal + "um click");


            } else {
                if (document.querySelector("#ModalExcluir").style.display == "none") {
                    document.querySelector(".modal-dialog").style.marginTop = (mouse.page.y - 100) + "px";
                    console.log("entrou")

                } else {

                }
            }

        });

    $(document).ready(function () {

        var IDCargo;
        var IDFuncionario = 0;
        var request = true;

        $(".AbrirModal").click(function () {
            IDCargo = $(this).attr("data-id");
            $("#ModalExcluir").modal('show');
            $("#Excluir").removeAttr("disabled");
            $("#BtnNao").removeAttr("disabled");
            $("#Confirmacao").html("Tem certeza que deseja excluir esse cargo?");
        });

        $("#Excluir").click(function () {
            $("#Confirmacao").css("display", "none");
            $("#Carregando").css("display", "block");
            $(this).attr("disabled", "disabled");
            $("#BtnNao").attr("disabled", "disabled");

            var url = "@Url.Action("ExcluirCargo","Cargo")";

            $.post(url, { id: IDCargo }, RespostaServidor);

        });

        function RespostaServidor(retorno) {
                $("#Confirmacao").html(retorno);
                $("#Confirmacao").css("display", "block");
                $("#Carregando").css("display", "none");

                if (retorno == "O cargo foi excluído com sucesso!") {
                    $("#Cargo-" + IDCargo).slideUp('slow');
                }

            }
    });
    </script>
}