RH.View/Controllers/DadosBancariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.Model;
using RH.Control;
using RH.View.CriptoHelper;
using RH.View.Filtro;

namespace RH.View.Controllers
{
    [AutorizacaoEmpresa]
    public class DadosBancariosController : Controller
    {

        private CDadoBancario _Control;

        public DadosBancariosController()
        {
            _Control = new CDadoBancario();
        }

        // GET: DadosBancarios
        public ActionResult Index(string IDFuncionario)
        {
            int IDDescriptografado = Convert.ToInt32(Criptografia.DecriptQueryString(IDFuncionario));

            List<DadoBancario> Dados = _Control.DadosBanacarioFuncionario(IDDescriptografado);
            Pessoa aPessoa = _Control.SelecionarFuncionario(IDDescriptografado);
            ViewBag.IDFuncionario = IDFuncionario;
            ViewBag.NomeFuncionario = aPessoa.Pes_Nome;
            return View(Dados);
        }

        public ActionResult CadastrarDadoBancario(string IDFuncionario)
        {
            ViewBag.IDFuncionario = IDFuncionario;
            int IDDescriptografado = Convert.ToInt32(Criptografia.DecriptQueryString(IDFuncionario));
            Pessoa oFuncionario = _Control.SelecionarFuncionario(IDDescriptografado);
            ViewBag.NomeFuncionario = oFuncionario.Pes_Nome;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarDadoBancario(DadoBancario oDado,string IDFuncionario)
        {
            int IDDescriptografado = Convert.ToInt32(Criptografia.DecriptQueryString(IDFuncionario));
            Pessoa aPessoa = _Control.SelecionarFuncionario(IDDescriptografado);
            ViewBag.IDFuncionario = IDFuncionario;
            ViewBag.NomeFuncionario = aPessoa.Pes_Nome;

            if (Convert.ToBoolean(Session["Avaliativa"]))
            {
                if (_Control.LimiteDadosBancariosEmpresaAvaliativa(Convert.ToInt32(Session["IDEmpresa"])))
                {
                    ModelState.AddModelError("Limite", "O limite de dados bancários nessa Empresa Avaliativa foi atingido. (Limite de Dados Bancários = 5)");
                }
            }

            if (ModelState.IsValid)
            {
                Empresa aEmpresa = _Control.SelecionarEmpresa(Convert.ToInt32(Session["IDEmpresa"]));
                oDado.DB_DataCadastro = aEmpresa.Emp_DataAtual;
                oDado.DB_Pessoa_Pes_ID = IDDescriptografado;
                oDado.DB_Situation = true;
                _Control.CadastrarDadoBancario(oDado);
                return RedirectToAction("Index",new { IDFuncionario=IDFuncionario});
            }

            return View();
        }

        public ActionResult AlterarDadoBancario(int IDDadoBancario,int IDFuncionario)
        {
            Pessoa aPessoa = _Control.SelecionarFuncionario(IDFuncionario);
            ViewBag.IDFuncionario = IDFuncionario;
            ViewBag.NomeFuncionario = aPessoa.Pes_Nome;

            DadoBancario oDado = _Control.SelecionarDadoBancario(IDDadoBancario);
            return View(oDado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarDadoBancario(DadoBancario oDado,int IDFuncionario)
        {
            Pessoa aPessoa = _Control.SelecionarFuncionario(IDFuncionario);
            ViewBag.IDFuncionario = IDFuncionario;
            ViewBag.NomeFuncionario = aPessoa.Pes_Nome;

            if(ModelState.IsValid)
            {
                DadoBancario DadoBancarioAlterar = _Control.SelecionarDadoBancario(oDado.DB_ID);
                DadoBancarioAlterar.DB_Numero = oDado.DB_Numero;
                DadoBancarioAlterar.DB_Tipo = oDado.DB_Tipo;
                _Control.AlterarDadoBancario(DadoBancarioAlterar);
                return RedirectToAction("Index",new { IDFuncionario=IDFuncionario});
            }

            return View();
        }

        public ActionResult ExcluirDadoBancario(int id)
        {
            DadoBancario oDado=_Control.SelecionarDadoBancario(id);
            oDado.DB_Situation = false;
            _Control.AlterarDadoBancario(oDado);
            return Json("Dado bancário excluído com sucesso!");
        }
    }
}

RH.View/Views/DadosBancarios/AlterarDadoBancario.cshtml
@model RH.Model.DadoBancario


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=>model.DB_ID)

        <div class="container my-4">
            <div class="card">

                <div class="card-header">
                    <h1>Cadastrar dado bancário</h1>
                </div>

                <div class="card-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DB_Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.DB_Tipo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DB_Tipo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DB_Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.DB_Numero, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DB_Numero, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Salvar</button>
                        </div>
                    </div>
                </div>

            </div>

        </div>



    </div>
}

<div class="back">
    <a href="@Url.Action("Index","DadosBancarios",new { IDFuncionario=ViewBag.IDFuncionario})"><i class="fas fa-arrow-left"></i> Voltar</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RH.View/Views/DadosBancarios/CadastrarDadoBancario.cshtml
@model RH.Model.DadoBancario


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="container my-4">
        <div class="card">

            <div class="card-header">
                <h1>Cadastrar dado bancário</h1>
            </div>

            <div class="card-body">
                <div align="center" class="col-md-12 form-group">
                    @Html.ValidationMessage("Limite", "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DB_Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.DB_Tipo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DB_Tipo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DB_Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.DB_Numero, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DB_Numero, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Cadastrar</button>
                    </div>
                </div>
            </div>

        </div>

    </div>



</div>
}

    <div class="back">
        <a href="@Url.Action("Index","DadosBancarios",new { IDFuncionario=ViewBag.IDFuncionario})"><i class="fas fa-arrow-left"></i> Voltar</a>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RH.View/Views/DadosBancarios/Index.cshtml
@model IEnumerable<RH.Model.DadoBancario>
@Styles.Render("~/Content/Pages/css")



<br />
<a class="btn btn-success custom" href="@Url.Action("CadastrarDadoBancario","DadosBancarios",new { IDFuncionario=ViewBag.IDFuncionario})"><span class="fa fa-plus"></span> Cadastrar novo dado bancário</a>
<br />
<hr />

<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <h1>Benefícios do Funcionário @ViewBag.NomeFuncionario</h1>
        </div>
        <div class="card-body">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered text-center">
                    <tr style="background-color: rgb(148,72,72);" class="text-white">
                        <th>
                            @Html.DisplayNameFor(model => model.DB_Tipo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DB_Numero)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DB_DataCadastro)
                        </th>
                        <th>Ações</th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr id="Dado-@item.DB_ID">
                            <td>
                                @Html.DisplayFor(modelItem => item.DB_Tipo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DB_Numero)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DB_DataCadastro)
                            </td>
                            <td>
                                <a class="btn btn-warning custom" href="@Url.Action("AlterarDadoBancario","DadosBancarios",new { IDDadoBancario=item.DB_ID,IDFuncionario=ViewBag.IDFuncionario})"><i class="fas fa-user-edit"></i> Alterar</a>
                                <button class="btn btn-danger custom AbrirModal" data-id="@item.DB_ID"><i class="fas fa-user-times"></i> Excluir</button>
                            </td>
                        </tr>
                    }

                </table>
            }

            else
            {
                <div class="alert alert-primary" role="alert">
                    <div class="alert-body">
                        <h4>Este Funcionário não possui nenhum dado bancário cadastrado</h4>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

<hr />

<div class="back">
    <a href="~/Pessoa/MeusFuncionarios"><i class="fas fa-arrow-left"></i> Voltar</a>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="ModalDadoBancario">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir Dado Bancário</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="Mensagem">
                </div>
                <div id="Carregando" align="center" style="display:none;">
                    <img src="~/Imagem/833.gif" />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success BtnModal" id="ExcluirDado">Sim</button>
                <button type="button" class="btn btn-danger BtnModal" data-dismiss="modal" id="BtnNao">Não</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script>

       

        $(document).ready(function () {

            var IDDadoBancario;

            $(".AbrirModal").click(function () {

                IDDadoBancario = $(this).attr("data-id");
                $("#ModalDadoBancario").modal('show');
                $("#Mensagem").html("Tem certeza que deseja excluir esse dado bancário?");
                $(".BtnModal").removeAttr("disabled");

            });

            $("#ExcluirDado").click(function () {

                $("#Mensagem").css("display", "none");
                $("#Carregando").css("display", "block");
                $(".BtnModal").attr("disabled", "disabled");

                var url = "@Url.Action("ExcluirDadoBancario","DadosBancarios")";

                $.post(url, { id: IDDadoBancario },Output)

            });

            function Output(retorno) {

                $("#Mensagem").css("display", "block");
                $("#Carregando").css("display", "none");
                $("#Mensagem").html(retorno);

                $("#Dado-" + IDDadoBancario).slideUp('slow');
            }

        });

    </script>


    }