RH.View/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.Model;
using RH.Control;
using PagedList;
using RH.View.Filtro;
using RH.View.CriptoHelper;

namespace RH.View.Controllers
{
    [Autorizacao]
    public class EmpresaController : Controller
    {
        private CEmpresa _Control;

        public EmpresaController()
        {
            _Control = new CEmpresa();
        }

        // GET: Empresa
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MinhasEmpresas(int? pagina)
        {
            Session["IDEmpresa"] = null;

            int paginaTamanho = 4;
            int paginaNumero = (pagina ?? 1);
            Aluno oAluno = (Aluno)Session["User"];
            List<Empresa> MinhasEmpresas = _Control.SelecionarTodasEmpresasAluno(oAluno.Alu_ID);

            Prova aProva = _Control.ProvaAluno(oAluno.Alu_ID);

            if(aProva!=null)
            {
                ViewBag.DataTermino = aProva.Pro_DataTermino;
            }

            aProva = _Control.SelecionarProvaEntregue(oAluno.Alu_ID);
            if(aProva!=null && DateTime.Compare(aProva.Pro_DataTermino.Date,DateTime.Now.Date)<=0)
            {
                Nota aNota = _Control.SelecionarNotaProva(aProva.Pro_ID);
                if(aNota.Not_Nota<10)
                {
                    ViewBag.Nota = aNota.Not_Nota;
                    ViewBag.NomeAluno = oAluno.Alu_Nome;
                    ViewBag.DataEntrega = aNota.Not_DataCadastro;
                    ViewBag.IDProva = aProva.Pro_ID;                    
                }
               
            }

            return View(MinhasEmpresas.ToPagedList(paginaNumero, paginaTamanho));
        }

        public ActionResult CadastrarEmpresa()
        {
            Aluno oAluno = (Aluno)Session["User"];
            Prova aProva = _Control.ProvaAluno(oAluno.Alu_ID);

            if (aProva != null)
            {
                ViewBag.DataTermino = aProva.Pro_DataTermino;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarEmpresa(Empresa aEmpresa, HttpPostedFileBase Imagem,bool Avaliativa=false)
        {
            Aluno oAluno = (Aluno)Session["User"];

            Prova aProva = _Control.ProvaAluno(oAluno.Alu_ID);

            if (aProva != null)
            {
                ViewBag.DataTermino = aProva.Pro_DataTermino;
            }

            if (Avaliativa)
            {
                if (_Control.EmpresaAvaliativaAtiva(oAluno.Alu_ID))
                {
                    ModelState.AddModelError("EmpresaAvaliativa", "Você já possui uma empresa avaliativa, você não pode ter duas empresas avaliativas cadastradas ao mesmo tempo.");
                    return View();
                }
            }
            
            if (Imagem != null)
            {
                byte[] Arquivo = new byte[Imagem.ContentLength];
                Imagem.InputStream.Read(Arquivo, 0, Imagem.ContentLength);
                aEmpresa.Emp_Logo = Arquivo;
            }

            else
            {
                ModelState.AddModelError("Imagem", "Por favor selecione uma logo para sua empresa");
                return View();
            }

            if (ModelState.IsValid)
            {
                aEmpresa.Emp_DataCadastro = DateTime.Now;
                aEmpresa.Emp_DataAtual = "01/01";
                aEmpresa.Emp_Situation = true;               
                aEmpresa.Emp_Aluno_Alu_ID = Convert.ToInt32(oAluno.Alu_ID);
                aEmpresa.Emp_Avaliativa = Avaliativa;
                _Control.CadastrarEmpresa(aEmpresa);
                return RedirectToAction("MinhasEmpresas");
            }
            return View();
        }
    
        public ActionResult EditarEmpresa(string id)
        {
            Empresa aEmpresa = _Control.SelecionarEmpresa(Convert.ToInt32(Criptografia.DecriptQueryString(id)));
            return View(aEmpresa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarEmpresa(Empresa aEmpresa,HttpPostedFileBase Imagem)
        {
            Empresa empresa = _Control.SelecionarEmpresa(aEmpresa.Emp_ID);

            if (!ModelState.IsValid)
            {
                return View(aEmpresa);
            }

            if (Imagem != null)
            {
                byte[] imagem = new byte[Imagem.ContentLength];
                Imagem.InputStream.Read(imagem, 0, Imagem.ContentLength);
                empresa.Emp_Logo = imagem;
            }

            empresa.Emp_Nome = aEmpresa.Emp_Nome;
            empresa.Emp_Estado = aEmpresa.Emp_Estado;
            empresa.Emp_Cidade = aEmpresa.Emp_Cidade;
            empresa.Emp_Endereco = aEmpresa.Emp_Endereco;
            empresa.Emp_CNPJ = aEmpresa.Emp_CNPJ;
            empresa.Emp_RegistroEstadual = aEmpresa.Emp_RegistroEstadual;

            _Control.AlterarEmpresa(empresa);
            return RedirectToAction("Index","Home",new { id=empresa.Emp_ID,nomeEmpresa=empresa.Emp_Nome});

        }

        public ActionResult GetImagem(int id)
        {
            Empresa aEmpresa = _Control.SelecionarEmpresa(id);
            return File(aEmpresa.Emp_Logo, aEmpresa.Emp_Logo.GetType().ToString());
        }
    }
}

RH.View/Controllers/ProvaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RH.Model;
using RH.Control;
using System.Drawing;
using System.IO;
using System.Drawing.Imaging;
using RH.View.Filtro;

namespace RH.View.Controllers
{
    
    public class ProvaController : Controller
    {
        CProva _Control;

        public ProvaController()
        {
            _Control = new CProva();
        }

        public string SelecionarNome()
        {
            string[] Nomes = new string[100] { "Abílio Carneiro",
            "Adalberto Fernández",
            "Adelaide Junqueira",
            "Adelaide Vilanova",
            "Adelina Angelim",
            "Aida Cortês",
            "Américo Mariz",
            "Amílcar Belén",
            "Angelino Cayubi",
            "Anna Taperebá",
            "António Muniz",
            "Aníbal Leal",
            "Berengária Brandão",
            "Bernardina Godoi",
            "Boaventura Castella",
            "Brenda Conceição",
            "Bukake Canhão",
            "Bukake Maranhão",
            "Burtira Pinheiro",
            "Caetano Ferreyra",
            "Carolina Borges",
            "Casimiro Rangel",
            "Caubi Covilhã",
            "Cauã Suaçuna",
            "Cândida Barreto",
            "Davide Valentín",
            "Deise Baranda",
            "Delfina Bacelar",
            "Délia Durão",
            "Ema Uchoa",
            "Emiliana Teves",
            "Estefânia Carreiro",
            "Eugénia Sanches",
            "Evangelista Maciel",
            "Evaristo Dourado",
            "Filipa Giménez",
            "Flávio Vilarim",
            "Frederico Mirandela",
            "Fábia Torcato",
            "Godofredo Athayde",
            "Graça Guará",
            "Gregório Xavier",
            "Guido Freitas",
            "Guilhermina Carromeu",
            "Guiomar Guimaraens",
            "Gávio Lagos",
            "Helena Barroqueiro",
            "Herberto Diniz",
            "Hermígio Beltrão",
            "Hernâni Moreira",
            "Ifigénia Vides",
            "Jacira Silveira dos Açores",
            "Jandira Beltrão",
            "Jerónimo, Jerônimo Junquera",
            "Jerónimo, Jerônimo Sant'Anna",
            "Joaquim Bencatel",
            "Joaquim Gentil",
            "Jónatas Sousa de Arronches",
            "Júlio Salazar",
            "Luciano Montero",
            "Lucinda Siebra",
            "Luísa Lage",
            "Lília Carrasqueira",
            "Mafalda Perdigón",
            "Mafalda Tabosa",
            "Mamede Maciel",
            "Mbicy Maciel",
            "Morgana Candeias",
            "Natividade Rivas",
            "Odilia Jorge",
            "Palmira Cardozo",
            "Pandora Díaz",
            "Quirino Briones",
            "Raquel Goes",
            "Raquel Ríos",
            "Romano Lamego",
            "Roque Jucá",
            "Rui Villaverde",
            "Rúben Roriz",
            "Salomão Marroquim",
            "Salvina Fialho",
            "Sebastião Gutiérrez",
            "Severino Tupinambá",
            "Sofia Marinho",
            "Solano Inês",
            "Suniário Liberato",
            "Tadeu Padilha",
            "Taíssa Viegas",
            "Ubirajara Camilo",
            "Ubiratã Ribas",
            "Udo Varella",
            "Vanessa Piratininga",
            "Viriato Cachão",
            "Vitória Ornellas",
            "Vânia Talhão",
            "Xênia Parracho",
            "Zeferino Açores",
            "Zélia Domínguez",
            "Átila Ávila",
            "Énia Viveros"
            };

            int posicao;

            Random random = new Random();
            posicao = random.Next(0, 99);

            return Nomes[posicao];
        }

        public string SelecionarEndereco()
        {
            string[] Enderecos = new string[80]
            {
                    "Vila Verde",
                    "Novo Surubi",
                    "Surubi",
                    "Jardim Esperança",
                    "Morada da Barra",
                    "Jardim do Sol",
                    "Parque Embaixador",
                    "Fazenda da Barra 1",
                    "Fazenda da Barra 2",
                    "Fazenda da Barra 3",
                    "Nossa Senhora de Fátima",
                    "Campo Belo",
                    "Maria Cândida",
                    "Isaac Politi",
                    "Morro do Batista",
                    "Morro do Machado",
                    "Vila Moderna",
                    "Jardim Brasília 1",
                    "Jardim Brasília 2",
                    "Parque Ipiranga 1",
                    "Parque Ipiranga 2",
                    "Morada das Garças",
                    "Vicentina",
                    "Santo Amaro",
                    "Eucaliptal",
                    "Terras Alpha",
                    "Vila Julieta",
                    "Santa Cecília",
                    "Jardim Jalisco",
                    "Liberdade",
                    "Nova Liberdade",
                    "Manejo",
                    "Vila Santa Isabel",
                    "Elite",
                    "Morada da Felicidade",
                    "Baixada da Olaria",
                    "Itapuca",
                    "Residencial Limeira",
                    "Morada da Colina 1",
                    "Morada da Colina 2",
                    "Morada da Colina 3",
                    "Mirante das Agulhas",
                    "Residencial Morada das Agulhas",
                    "Morada do Bosque",
                    "Casa da Lua",
                    "Loteamento Cícero",
                    "Alegria 1",
                    "Alegria 2",
                    "Nova Alegria",
                    "Jardim Alegria",
                    "Cidade Alegria",
                    "Nova Resende",
                    "Boa Vista 1",
                    "Boa Vista 2",
                    "Mirante da Serra",
                    "Morada da Montanha",
                    "Morada do Contorno",
                    "Jardim Beira Rio",
                    "Vila Isabel",
                    "Primavera 1",
                    "Primavera 2",
                    "Primavera 3",
                    "Jardim Aliança",
                    "Jardim do Oeste",
                    "Morada do Castelo",
                    "Montese",
                    "Bairro Comercial",
                    "Monte Castelo",
                    "Guararapes",
                    "Independência",
                    "Cabral",
                    "Alambari",
                    "Paraíso",
                    "Castelo Branco",
                    "Morro do Cruzeiro",
                    "Vila Araújo",
                    "Comercial",
                    "Jardim Tropical",
                    "São Caetano",
                    "Monet"
            };

            int posicao;

            Random random = new Random();
            posicao = random.Next(0, 79);

            return Enderecos[posicao];
        }

        [AutorizacaoProfessor]
        // GET: Prova
        public ActionResult Index()
        {
            List<Aluno> Alunos = _Control.SelecionarTodosAlunos();
            ViewBag.QuantidadeAlunos = Alunos.Count();

            List<VW_Provas> Provas = _Control.SelecionarTodasProva();
            return View(Provas);
        }

        [AutorizacaoProfessor]
        public ActionResult CadastrarProva(string DataTermino)
        {
            bool ProvaAtiva = _Control.ProvaAtiva();
            if(ProvaAtiva)
            {
                return Json("3");
            }

            DateTime Data = Convert.ToDateTime(DataTermino);

            if (DateTime.Compare(DateTime.Now.Date, Data) == 0)
            {
                return Json("0");
            }

            else if (DateTime.Compare(Data, DateTime.Now.Date) < 0)
            {
                return Json("1");
            }

            byte[] data;
            
            var caminho = Server.MapPath("~/Imagem/sem-imagem-avatar.png");
            Bitmap bmp = new Bitmap(caminho);

            MemoryStream memory = new MemoryStream();
            bmp.Save(memory, ImageFormat.Bmp);

            data = memory.ToArray();

            List<Aluno> Alunos = _Control.SelecionarTodosAlunos();


            int CodigoProva = _Control.QuantidadeProvas()+1;

            foreach(var x in Alunos)
            {

                Prova aProva = new Prova();
                Professor oProfessor = (Professor)Session["User"];
                aProva.Pro_Professor_Pro_ID = oProfessor.Pro_ID;
                aProva.Pro_Aluno_Alu_ID = x.Alu_ID;
                aProva.Pro_DataInicio = DateTime.Now;
                aProva.Pro_DataTermino = Convert.ToDateTime(DataTermino);

                int IDAlunoProva = 0;
                Aluno oAluno = _Control.AlunoProva();
                if(oAluno==null)
                {
                    Aluno AlunoProva = new Aluno();
                    AlunoProva.Alu_Curso_Cur_ID = 1;
                    AlunoProva.Alu_DataCadastro = DateTime.Now;
                    AlunoProva.Alu_Email = "ALUNO PROVA";
                    AlunoProva.Alu_Matricula = 1;
                    AlunoProva.Alu_Nome = "ALUNO PROVA";
                    AlunoProva.Alu_Senha = "ALUNO PROVA";
                    AlunoProva.Alu_Serie = 1;
                    AlunoProva.Alu_Situation = false;
                    _Control.CadastrarAluno(AlunoProva);
                    IDAlunoProva = AlunoProva.Alu_ID;
                }

                else
                {
                    IDAlunoProva = oAluno.Alu_ID;
                }

                Empresa aEmpresa = _Control.EmpresaAlunoProva();
                int IDEmpresaProva;

                if(aEmpresa==null)
                {
                    Empresa EmpresaAlunoProva = new Empresa();
                    EmpresaAlunoProva.Emp_Nome = "EMPRESA";

RH.View/Views/Empresa/CadastrarEmpresa.cshtml
@model RH.Model.Empresa

@{
    Layout = "~/Views/Shared/LayoutSemMenu.cshtml";
}

@{
    ViewBag.Title = "Cadastrar Empresa";

    bool Possui = false;

    if (ViewBag.DataTermino != null)
    {
        Possui = true;
    }
}




@using (Html.BeginForm("CadastrarEmpresa", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <h1>Cadastrar Empresa</h1>
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-12">
                    <input type="file" name="Imagem" id="Imagem" data-preview-file-type="text" data-msg-placeholder="Selecione uma Logo para sua empresa" />
                    @Html.ValidationMessage("Imagem", "", new { @class = "text-danger" })


                </div>



                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_Nome, htmlAttributes: new { })

                    @Html.EditorFor(model => model.Emp_Nome, new { htmlAttributes = new { @class = "form-control ", @type = "text", @placeholder = "Digite o Nome da Empresa" } })
                    @Html.ValidationMessageFor(model => model.Emp_Nome, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_Estado, htmlAttributes: new { @class = "control-label " })
                    <select id="estado" name="Emp_Estado" class="form-control">
                        <option disabled selected>Selecione o estado da Empresa</option>
                        <option value="Acre">Acre</option>
                        <option value="Alagoas">Alagoas</option>
                        <option value="Amapá">Amapá</option>
                        <option value="Amazonas">Amazonas</option>
                        <option value="Bahia">Bahia</option>
                        <option value="Ceará">Ceará</option>
                        <option value="Distrito Federal">Distrito Federal</option>
                        <option value="Espírito Santo">Espírito Santo</option>
                        <option value="Goiás">Goiás</option>
                        <option value="Maranhão">Maranhão</option>
                        <option value="Mato Grosso">Mato Grosso</option>
                        <option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
                        <option value="Minas Gerais">Minas Gerais</option>
                        <option value="Pará">Pará</option>
                        <option value="Paraíba">Paraíba</option>
                        <option value="Paraná">Paraná</option>
                        <option value="Pernambuco">Pernambuco</option>
                        <option value="Piauí">Piauí</option>
                        <option value="Rio de Janeiro">Rio de Janeiro</option>
                        <option value="Rio Grande do Norte">Rio Grande do Norte</option>
                        <option value="Rio Grande so Sul">Rio Grande do Sul</option>
                        <option value="Rondônia">Rondônia</option>
                        <option value="Roraima">Roraima</option>
                        <option value="Santa Catarina">Santa Catarina</option>
                        <option value="São Paulo">São Paulo</option>
                        <option value="Sergipe">Sergipe</option>
                        <option value="Tocantins">Tocantins</option>
                        <option value="Estrangeiro">Estrangeiro</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.Emp_Estado, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_Cidade, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Emp_Cidade, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite a Cidade da Empresa" } })
                        @Html.ValidationMessageFor(model => model.Emp_Cidade, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_Endereco, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Emp_Endereco, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o Endereço da Empresa" } })
                        @Html.ValidationMessageFor(model => model.Emp_Endereco, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_CNPJ, htmlAttributes: new { @class = "control-label " })
                    <div class="">
                        @Html.EditorFor(model => model.Emp_CNPJ, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o CNPJ da Empresa" } })
                        @Html.ValidationMessageFor(model => model.Emp_CNPJ, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Emp_RegistroEstadual, htmlAttributes: new { @class = "control-label " })
                    <div class="">
                        @Html.EditorFor(model => model.Emp_RegistroEstadual, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o Registro Estadual da Empresa" } })
                        @Html.ValidationMessageFor(model => model.Emp_RegistroEstadual, "", new { @class = "text-danger" })
                    </div>
                </div>

                @if (Possui)
                {
                    <div class="form-group col-md-12" align="center">
                        <label class="control-label">Está empresa é uma Empresa Avaliativa?</label>
                        <br />
                        <label class='mr-4'><input type='radio' name='Avaliativa' value='true' id='Avaliativa' /> Sim</label>
                        <label class='mr-4'><input type='radio' name='Avaliativa' value='false' id='demitido' checked /> Não</label>
                        <br />
                        @Html.ValidationMessage("EmpresaAvaliativa", "", new { @class = "text-danger" })
                    </div>
                }



            </div>
        </div>
        <div class="card-footer">
            <div class="from-group col-md-12">
                <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Cadastrar</button>
            </div>
        </div>
    </div>
</div>

}

<div class="back">
    <a href="~/Empresa/MinhasEmpresas"><i class="fas fa-arrow-left"></i> Voltar</a>

</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#Imagem").fileinput({ language: "pt-BR", 'showUpload': false, 'previewFileType': 'any' });
            $("#Imagem").change(function (e) {
                for (var i = 0; i < e.originalEvent.srcElement.files.length; i++) {
                    var file = e.originalEvent.srcElement.files[i];

                    var reader = new FileReader();
                    reader.onloadend = function () {
                        $("#aImagem").attr("src", reader.result);
                    }
                    reader.readAsDataURL(file);
                }
            });

            $("#aImagem").mouseover(function () {
                $(this).css("cursor", "pointer");
                $(this).css("width", "150%");
                $(this).css("heigth", "240px");
            });
        });
    </script>
}

RH.View/Views/Empresa/EditarEmpresa.cshtml
@model RH.Model.Empresa

@{
    ViewBag.Title = "Editar Empresa";
}
<style>
    #info-img {
        display: none;
        color: gray;
    }

    .fa-question-circle {
        color: gray;
    }
</style>



@using (Html.BeginForm(Html.BeginForm("EditarEmpresa", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Emp_ID)

    <div class="container my-4">
        <div class="card">
            <div class="card-header">
                <h1>Alterar Empresa</h1>
            </div>
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <input type="file" name="Imagem" id="Imagem" data-preview-file-type="text" data-msg-placeholder="Selecione uma Logo para sua empresa" />
                        @Html.ValidationMessage("Imagem", "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_Nome, htmlAttributes: new { })

                        @Html.EditorFor(model => model.Emp_Nome, new { htmlAttributes = new { @class = "form-control ", @type = "text", @placeholder = "Digite o Nome da Empresa" } })
                        @Html.ValidationMessageFor(model => model.Emp_Nome, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_Estado, htmlAttributes: new { @class = "control-label " })

                        <select id="estado" name="Emp_Estado" class="form-control">
                            <option disabled selected>@Model.Emp_Estado</option>
                            <option value="Acre">Acre</option>
                            <option value="Alagoas">Alagoas</option>
                            <option value="Amapá">Amapá</option>
                            <option value="Amazonas">Amazonas</option>
                            <option value="Bahia">Bahia</option>
                            <option value="Ceará">Ceará</option>
                            <option value="Distrito Federal">Distrito Federal</option>
                            <option value="Espírito Santo">Espírito Santo</option>
                            <option value="Goiás">Goiás</option>
                            <option value="Maranhão">Maranhão</option>
                            <option value="Mato Grosso">Mato Grosso</option>
                            <option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
                            <option value="Minas Gerais">Minas Gerais</option>
                            <option value="Pará">Pará</option>
                            <option value="Paraíba">Paraíba</option>
                            <option value="Paraná">Paraná</option>
                            <option value="Pernambuco">Pernambuco</option>
                            <option value="Piauí">Piauí</option>
                            <option value="Rio de Janeiro">Rio de Janeiro</option>
                            <option value="Rio Grande do Norte">Rio Grande do Norte</option>
                            <option value="Rio Grande so Sul">Rio Grande do Sul</option>
                            <option value="Rondônia">Rondônia</option>
                            <option value="Roraima">Roraima</option>
                            <option value="Santa Catarina">Santa Catarina</option>
                            <option value="São Paulo">São Paulo</option>
                            <option value="Sergipe">Sergipe</option>
                            <option value="Tocantins">Tocantins</option>
                            <option value="Estrangeiro">Estrangeiro</option>
                        </select>

                        @Html.ValidationMessageFor(model => model.Emp_Estado, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_Cidade, htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.Emp_Cidade, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite a Cidade da Empresa" } })
                            @Html.ValidationMessageFor(model => model.Emp_Cidade, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_Endereco, htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.Emp_Endereco, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o Endereço da Empresa" } })
                            @Html.ValidationMessageFor(model => model.Emp_Endereco, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_CNPJ, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.EditorFor(model => model.Emp_CNPJ, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o CNPJ da Empresa" } })
                            @Html.ValidationMessageFor(model => model.Emp_CNPJ, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.Emp_RegistroEstadual, htmlAttributes: new { @class = "control-label " })
                        <div class="">
                            @Html.EditorFor(model => model.Emp_RegistroEstadual, new { htmlAttributes = new { @class = "form-control", @type = "text", @placeholder = "Digite o Registro Estadual da Empresa" } })
                            @Html.ValidationMessageFor(model => model.Emp_RegistroEstadual, "", new { @class = "text-danger" })
                        </div>
                    </div>





                </div>
            </div>
            <div class="card-footer">
                <div class="from-group col-md-12">
                    <button type="submit" class="btn btn-outline-secondary"><span class="fa fa-plus"></span> Salvar</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        document.querySelector(".fa-question-circle").addEventListener("click", () => {
            var a = (document.getElementById("info-img").style.display);
            if (a == "none") {
                document.getElementById("info-img").style.display = "inline";
            } else {
                document.getElementById("info-img").style.display = "none";
            }

        });
    </script>

    <script>
        $(document).ready(function () {
            $("#Imagem").fileinput({ language: "pt-BR", 'showUpload': false, 'previewFileType': 'any' });
            $("#Imagem").change(function (e) {
                for (var i = 0; i < e.originalEvent.srcElement.files.length; i++) {
                    var file = e.originalEvent.srcElement.files[i];

                    var reader = new FileReader();
                    reader.onloadend = function () {
                        $("#aImagem").attr("src", reader.result);
                    }
                    reader.readAsDataURL(file);
                }
            });

            $("#aImagem").mouseover(function () {
                $(this).css("cursor", "pointer");
                $(this).css("width", "150%");
                $(this).css("heigth", "240px");
            });

        });
    </script>
}